---
manifest:
  remotes:
  name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk_offical
      url: https://github.com/lynnlee0522/zmk_offical
      revision: main
      import: app/west.yml
  self:
    path: config