---
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - import: app/west.yml
      name: zmk
      remote: zmkfirmware
      revision: main
  self:
    path: config