---
manifest:
  remotes:
    - name: lynnlee0522
      url-base: https://github.com/lynnlee0522
  projects:
    - import: app/west.yml
      name: zmk_offical
      remote: lynnlee0522
      revision: main
  self:
    path: config