---
manifest:
  remotes:
    - name: zmk_offical
      url-base: https://github.com/lynnlee0522
  projects:
    - import: app/west.yml
      name: curie
      remote: zmk_offical
      revision: custom_screen
  self:
    path: config