---
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/lynnlee0522/zmk_offical.git
  projects:
    - import: app/west.yml
      name: zmk
      remote: zmkfirmware
      revision: custom_screen
  self:
    path: config